baseurl = "https://byronwoodfork.com"
theme = "ghostwriter"
languageCode = "en-us"
copyright = "Byron Woodfork"
googleAnalytics = "XXX"
disqusShortname = "XXX"

[Privacy]

[Privacy.disqus]
    disable = true

[Privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = false

[Author]
    name = "My Name"
    profile = "https://google.com/+XXX"

[Taxonomies]
    tag = "tags"

[Params]
    intro = true
    headline = "Byron Woodfork"
    description = "A blog about software development, career advice, mentoring and leadership in tech"
    github = "https://github.com/bwoodfork"
    linkedin = "https://linkedin.com/in/byronwoodfork/"
    twitter = "https://twitter.com/byronwoodfork"
    email = "byronwoodfork@gmail.com"
    opengraph = true
    shareTwitter = true
    shareLinkedIn = false
    dateFormat = "Mon, Jan 2, 2006"
    highlightJsUrl = ""
    highlightJsLocalUrl = ""
    exponeaJsUrl = ""
    exponeaTarget = ""
    exponeaToken = ""
    exponeaTrackVisits = false
    readingTime = true
    readingTimeText = "Estimated reading time:"

[Permalinks]
    post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Talks"
    url = "/talks/"
    weight = 2

[[menu.main]]
    name = "Contact"
    url = "/page/contact/"
    weight = 3

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 4